language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - COMMONMARK_VERSION=0.11.*
  - COMMONMARK_VERSION=0.12.*
  - COMMONMARK_VERSION=0.13.*
  - COMMONMARK_VERSION=0.14.*
  - COMMONMARK_VERSION=0.15.*

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then PHPUNIT_COVERAGE="--coverage-clover=coverage.clover"; else PHPUNIT_COVERAGE=""; fi
  - if [[ $TRAVIS_PHP_VERSION = '5.5' ]]; then COMPOSER_FLAGS="--prefer-lowest"; else COMPOSER_FLAGS=""; fi
  - composer self-update
  - if [ "$COMMONMARK_VERSION" != "" ]; then composer require "league/commonmark:${COMMONMARK_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit $PHPUNIT_COVERAGE

after_script:
  - if [[ "$PHPUNIT_COVERAGE" != "" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
